### ISSUE TITLE
Checking URL schemes in current form won’t work

### ISSUE THREAD

**Issue by kubajakowski** [securing/IOSSecuritySuite#2]
Hi!
Current way of checking URL schemes won’t work. As doc says, queried schemes must be added to application plist - otherwise you’ll always get `false` from `canOpenURL`
https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl

**Comment by r3ggi** [comment]
Hey,

Thanks for that info! I'll investigate it soon 😉I need also get to know why that way of checking URL schemes worked in my configuration (jailbroken iOS 11.4.1 and jailed 12.2).

**Comment by kubajakowski** [comment]
I don't have much experience with jailbroken devices - but maybe jailbreak changes/swizzles this behavior.

**Comment by r3ggi** [comment]
Hey Kuba!

It looks that specifying URLs in Info.plist for Cydia and Sileo is not required. Maybe the reason was to not cause problems with jailbreak detectors like this. However, ```undecimous``` URL that I query for needs to be added to Info.plist. 

So, I decided (to avoid problems in the future) to update the ```README.md``` and ask users to add all the 3 URL schemes to their Info.plist (https://github.com/securing/IOSSecuritySuite/commit/d1932ccc372017d818e757470b112598e02c3ab2). 

Thanks for pointing it out! I have added you also to contributors list 👏🏻
