### ISSUE TITLE
False positive Cydia URL Scheme

### ISSUE THREAD

**Issue by ThiagoMiranda** [securing/IOSSecuritySuite#40]
Hi,
We're using IOSSecuritySuite in our app and suddenly a lot of our clients started to get our App blocked ( which is our default behavior when a jailbreak is detected ) after the iOS 14.4 update. I really don't know if the update is the cause but we've managed to reproduce the detection in a "pure" iOS 14.4 ( bought from an oficial Apple reseller store ) and it indeed happens. 
Using the method:

```swift
let jailbreakStatus = IOSSecuritySuite.amIJailbrokenWithFailMessage()
if jailbreakStatus.jailbroken {
	print("This device is jailbroken")
	print("Because: \(jailbreakStatus.failMessage)")
} else {
	print("This device is not jailbroken")
}
```

The message is: "Cydia:\/\/ URL scheme detected". Does anyone reported this? Is there something we can do?

Thanks!

**Comment by r3ggi** [comment]
Hey,

I've just verified on iPhone 12 with iOS 14.4 and iPhone 12 Mini iOS 14.3 and the ISS seems to work properly.

Maybe your issue is related to https://github.com/securing/IOSSecuritySuite/issues/25 where the iPhones were not properly cleaned after jailbreaks. Please try to restore factory settings on your test iPhone via iTunes/Finder (so you will be sure that the whole filesystem has been wiped).

I'd also recommend to disable blocking users when the jailbreak is detected. You should inform user that using a jailbroken phone is risky and send that information on your servers.

**Comment by ThiagoMiranda** [comment]
We've tried in a completely brand new iPhone. Another strange behavior that we are experiencing is that users on Wifi don't fall on this detection but users using 4G fall. The same user with the same device.

**Comment by vocaeq** [comment]
Hi, 
Despite our efforts, we were unable to reproduce the problem. Could you provide us some more details? Type of device and the exact version of iOS would be much appreciated. Also, do I understand correctly that check only triggers when the device is not connected to wifi?

**Comment by ThiagoMiranda** [comment]
We're experiecing in different users with different devices. An example caught in our New Relic log ( we log the detection before stopping the app ):

Device: iPhone XS
iOS: 14.4
When this user uses Wifi the App doesn't detect any jailbreak. When he uses 4g it does.

We do a exit(0) when we detect an jailbreak:
```swift
guard NetworkReachabilityManager()?.isReachable ?? true else {
    exit(0)
}
```

**Comment by r3ggi** [comment]
How does the code you pasted:

```swift
guard NetworkReachabilityManager()?.isReachable ?? true else {
    exit(0)
}
```

is related to the ISS? Did I miss something?
