### ISSUE TITLE
[QUESTION] Reasoning behind main thread usage

### ISSUE THREAD

**Issue by ulusalomerwise** [securing/IOSSecuritySuite#98]
I am curious about why you are using main thread here. Why don't we call canOpenUrl in a background thread?

https://github.com/securing/IOSSecuritySuite/blob/1708ab502d8985ce1a1957128473fe866d9e965e/IOSSecuritySuite/JailbreakChecker.swift#L88-L122

**Comment by ulusalomerwise** [comment]
Here it says calling this function in a background thread is okay.

https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl

> You can call this method safely on a thread that isn’t the main thread.

**Comment by r3ggi** [comment]
Hey!

Yes, you're right. Thanks, I fixed it

**Comment by ObjectiveCesar** [comment]
Even though the documentation states that it is safe to call that function from a non-main thread, we have issues inside our app. The call to canOpenURL without making sure it's on the main thread is interfering with another framework we're using. Since there is no downside to using the main thread for this call (as it has been done before and for ages, like every other UIKit api) it should be put back as far as I#m concerned.
